
import React from 'react';
import PoultryMedicineCategories from './PoultryMedicineCategories';
import DogMedicineCard from './DogMedicineCard';
import CatMedicineCard from './CatMedicineCard';

interface MedicineGridProps {
  petType: string;
}

const MedicineGrid: React.FC<MedicineGridProps> = ({ petType }) => {
  // For birds, show categories instead of individual medicines
  if (petType === 'birds') {
    return <PoultryMedicineCategories />;
  }

  // Individual medicine data for each pet type
  const getMedicinesForPetType = () => {
    if (petType === 'dogs') {
      return [
        { id: 1, name: 'Meloxicam', description: 'Inhibits cyclooxygenase (COX), mainly COX-2, reducing inflammation, pain, and fever.', image: 'https://images.unsplash.com/photo-1551717743-49959800b1f6?w=400&h=300&fit=crop' },
        { id: 2, name: 'Ketoprofen', description: 'It inhibits the cyclooxygenase enzymes (COX-1 and COX-2), reducing the production of prostaglandins — chemicals responsible for inflammation, pain, and fever. This leads to its anti-inflammatory, analgesic (pain-relieving), and antipyretic (fever-reducing) effects.', image: 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=400&h=300&fit=crop' },
        { id: 3, name: 'Alphachymotrypsin', description: 'Alpha-chymotrypsin is a serine protease that breaks down proteins by cleaving peptide bonds, especially at aromatic amino acids (tyrosine, phenylalanine, tryptophan). It helps reduce inflammation, aid tissue repair, and decrease edema (swelling) in conditions like trauma or surgery.', image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop' },
        { id: 4, name: 'Carprofen', description: 'Carprofen works by inhibiting cyclooxygenase (COX) enzymes, particularly COX-2, which reduces the production of prostaglandins—chemicals responsible for pain, inflammation, and fever. This leads to reduced pain and inflammation, especially in conditions like arthritis or post-surgery recovery.', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop' },
        { id: 5, name: 'Dexamethasone', description: 'Dexamethasone works by binding to glucocorticoid receptors, leading to suppression of inflammation and immune responses. It decreases the production of inflammatory cytokines, inhibits prostaglandin synthesis, and reduces immune cell activity, making it effective for treating allergies, autoimmune diseases, and inflammation.', image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=300&fit=crop' },
        { id: 6, name: 'Prednisolone', description: 'Prednisolone works by binding to glucocorticoid receptors, leading to reduced inflammation and immune response. It inhibits the production of inflammatory mediators like prostaglandins and cytokines, helping to control conditions such as allergies, asthma, and autoimmune diseases.', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop' },
        { id: 7, name: 'Hydrocortisone', description: 'Hydrocortisone works by activating glucocorticoid receptors, leading to suppression of inflammation and immune responses. It decreases the production of pro-inflammatory cytokines and inhibits prostaglandin synthesis, helping manage conditions like skin inflammation, allergies, and adrenal insufficiency.', image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400&h=300&fit=crop' },
        { id: 8, name: 'Triamcinolone', description: 'Triamcinolone binds to glucocorticoid receptors, leading to suppression of inflammation and immune responses. It reduces the production of pro-inflammatory cytokines, inhibits prostaglandins, and decreases immune cell activity, making it effective for treating allergies, skin conditions, arthritis, and asthma.', image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop' },
        { id: 9, name: 'Drontal', description: 'Drontal is a broad-spectrum anthelmintic medication primarily used for deworming in pets (especially dogs and cats). Praziquantel paralyzes and destroys the outer layer of flatworms (tapeworms). Pyrantel pamoate targets roundworms and hookworms, paralyzing them and causing them to be expelled from the intestines. Febantel interferes with the worm metabolism and inhibits its ability to reproduce.', image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop' },
        { id: 10, name: 'Milbemax', description: 'Milbemax combines two active ingredients for broad-spectrum deworming. Milbemycin oxime binds to glutamate-gated chloride channels in parasite nerve cells, causing hyperpolarization, paralysis, and death. Praziquantel damages parasite cell membranes, causing muscle paralysis and structural disintegration, leading to immune elimination of the parasite.', image: 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=400&h=300&fit=crop' },
        { id: 11, name: 'Panacur', description: 'Panacur contains fenbendazole, a broad-spectrum anthelmintic that inhibits tubulin polymerization into microtubules, disrupting parasite intestinal cell function. This leads to nutrient absorption failure and parasite death. Effective against roundworms, hookworms, whipworms, and some tapeworms.', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop' },
        { id: 12, name: 'Albenidazole', description: 'Albendazole inhibits the polymerization of tubulin into microtubules in parasitic cells, disrupting their structure and metabolism, leading to parasite death. It also impairs glucose uptake, starving and eliminating the parasite.', image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=300&fit=crop' },
        { id: 13, name: 'Metronidazole', description: 'Metronidazole disrupts DNA synthesis in anaerobic microorganisms. It is reduced to reactive nitro radicals inside the microorganism, which bind to DNA, causing strand breakage and cell death. It is effective mainly against anaerobic bacteria and protozoa.', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop' },
        { id: 14, name: 'Imidocarb dipropionate', description: 'Imidocarb interferes with nucleic acid metabolism of protozoa by binding to DNA, disrupting replication and transcription. It may also inhibit polyamine synthesis, impairing parasite growth and viability. It is particularly effective against Babesia spp. due to accumulation in infected erythrocytes.', image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400&h=300&fit=crop' },
        { id: 15, name: 'Clindamycin', description: 'Clindamycin is a lincosamide antibiotic that inhibits protein synthesis in susceptible organisms. It binds to the 50S ribosomal subunit, blocking translocation during protein synthesis. In protozoa like Toxoplasma gondii and Plasmodium falciparum, it disrupts apicoplast function, leading to parasite death.', image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop' },
        { id: 16, name: 'Itraconazole', description: 'Itraconazole is an azole antifungal that inhibits the fungal cytochrome P450 enzyme (14α-demethylase). This prevents the conversion of lanosterol to ergosterol, an essential component of the fungal cell membrane. Disruption of ergosterol synthesis leads to increased membrane permeability and fungal cell death.', image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop' },
        { id: 17, name: 'Ketoconazole', description: 'Ketoconazole is an azole antifungal that inhibits lanosterol 14-α-demethylase (a cytochrome P450 enzyme), blocking the conversion of lanosterol to ergosterol. This destabilizes the fungal cell membrane and leads to fungal cell death.', image: 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=400&h=300&fit=crop' },
        { id: 18, name: 'Miconazole', description: 'Miconazole is an imidazole antifungal that inhibits ergosterol synthesis, a key component of fungal cell membranes. This disrupts membrane integrity, leading to increased permeability and fungal cell death.', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop' },
        { id: 19, name: 'Clavamox', description: 'Clavamox combines amoxicillin (a penicillin-type beta-lactam antibiotic) with clavulanic acid (a beta-lactamase inhibitor). Amoxicillin inhibits bacterial cell wall synthesis, causing cell lysis and death. Clavulanic acid protects amoxicillin from being broken down by beta-lactamase enzymes produced by resistant bacteria.', image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=300&fit=crop' },
        { id: 20, name: 'Amoxi-Tabs / Amoxi-Drops', description: 'Amoxi-Tabs and Amoxi-Drops are amoxicillin-only formulations. Amoxicillin works by inhibiting bacterial cell wall synthesis, leading to cell lysis and death. These forms are commonly prescribed for infections where beta-lactamase resistance is not a concern.', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop' },
        { id: 21, name: 'Ceftriaxone', description: 'Ceftriaxone is a broad-spectrum third-generation cephalosporin antibiotic used off-label in veterinary medicine, particularly for dogs and cats. It works by inhibiting bacterial cell wall synthesis through binding to penicillin-binding proteins (PBPs), leading to disruption of the cell wall, cell lysis, and bacterial death.', image: 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=400&h=300&fit=crop' },
        { id: 22, name: 'Metronidazole', description: 'Metronidazole is a widely used antibiotic and antiprotozoal agent. It is effective against anaerobic bacteria and protozoa. It works by being reduced inside anaerobic cells to reactive nitro radicals, which damage DNA, inhibit nucleic acid synthesis, and cause cell death. It selectively targets organisms with nitroreductase enzymes (anaerobes and protozoa). It has trade name of Flagyl (original brand by Sanofi).', image: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=400&h=300&fit=crop' },
        { id: 23, name: 'Baytril', description: 'Baytril is the brand name for enrofloxacin, a fluoroquinolone antibiotic. It works by inhibiting bacterial DNA gyrase and topoisomerase IV, enzymes necessary for DNA replication, transcription, and repair. This leads to bacterial cell death, making it bactericidal (kills bacteria rather than just inhibiting growth). It is widely used in dogs, cats, and other animals (including exotic species) for bacterial infections, especially when resistant to other antibiotics. Common indications include urinary tract infections (UTIs), skin infections (pyoderma), respiratory tract infections, wound infections, ear infections (otitis externa), gastrointestinal infections, prostatitis, and infections caused by Pseudomonas, E. coli, Staphylococcus, and other gram-negative and gram-positive bacteria. Baytril is not effective against anaerobic bacteria or fungi.', image: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=400&h=300&fit=crop' },
        { id: 24, name: 'Enroflox', description: 'Enroflox is a brand or generic name for enrofloxacin, a fluoroquinolone antibiotic. It inhibits bacterial DNA gyrase and topoisomerase IV — essential enzymes for DNA replication, transcription, and repair. This leads to rapid bacterial cell death (bactericidal). It is effective primarily against aerobic Gram-negative bacteria, and some Gram-positive bacteria. Enroflox is used in dogs, cats, and sometimes exotic animals or livestock. Common indications include skin infections (pyoderma, wounds), UTIs, respiratory infections, ear infections (otitis externa), gastrointestinal infections, bone and joint infections, prostatitis, and infections caused by E. coli, Klebsiella, Pasteurella, Staphylococcus, Pseudomonas, etc. Not effective against anaerobic bacteria or fungal infections.', image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400&h=300&fit=crop' },
        { id: 25, name: 'Cipromed', description: 'Cipromed contains ciprofloxacin, a fluoroquinolone antibiotic. It inhibits bacterial enzymes: DNA gyrase and topoisomerase IV, which are essential for DNA replication, repair, and transcription. Inhibition of these enzymes leads to bacterial DNA damage and cell death. Ciprofloxacin is bactericidal, primarily targeting aerobic gram-negative bacteria, and some gram-positive bacteria. Cipromed is primarily used in pets as an ophthalmic (eye drop) solution, though it may be prescribed off-label for other uses.', image: 'https://images.unsplash.com/photo-1601758123927-196f6b9f7b3f?w=400&h=300&fit=crop' },
        { id: 26, name: 'Ciprovet', description: 'Ciprovet contains ciprofloxacin, a fluoroquinolone antibiotic. It inhibits bacterial DNA gyrase and topoisomerase IV, enzymes required for bacterial DNA replication, repair, and transcription. This disruption leads to bacterial cell death. It is bactericidal and mainly effective against aerobic gram-negative bacteria and some gram-positive strains. Ciprovet is primarily used in dogs and cats for treating bacterial eye infections, though oral ciprofloxacin may occasionally be used off-label.', image: 'https://images.unsplash.com/photo-1596495577886-d920f1fb7238?w=400&h=300&fit=crop' },
        { id: 27, name: 'Amiglyde-V', description: 'Amiglyde-V contains amikacin sulfate, an aminoglycoside antibiotic. It works by binding irreversibly to the 30S ribosomal subunit of susceptible bacteria, inhibiting protein synthesis and producing faulty proteins, which leads to bacterial cell death. Amikacin is bactericidal and effective primarily against aerobic Gram-negative bacteria and some Gram-positive strains. It is typically reserved for serious infections that are resistant to other antibiotics.', image: 'https://images.unsplash.com/photo-1572715376041-6d374f580bd7?w=400&h=300&fit=crop' },
        { id: 28, name: 'Dog Liver Support Tablets', description: 'Herbal liver support for detox and health.', image: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400&h=300&fit=crop' },
        { id: 29, name: 'Dog Allergy Shampoo', description: 'Gentle shampoo for dogs with sensitive skin.', image: 'https://images.unsplash.com/photo-1561037404-61cd46aa6153?w=400&h=300&fit=crop' },
        { id: 30, name: 'Dog Recovery Kit', description: 'Complete post-op care kit for dogs after surgery.', image: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=400&h=300&fit=crop' },
        { id: 31, name: 'OmegaFur Skin & Coat Oil', description: 'Omega-rich oil supplement for shiny coat and reduced shedding.', image: 'https://images.unsplash.com/photo-1601758123837-1ec2e1e8eaf8?w=400&h=300&fit=crop' },
        { id: 32, name: 'HydraPurr Electrolyte Formula', description: 'Oral hydration support for cats during illness or heat stress.', image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400&h=300&fit=crop' },
        { id: 33, name: 'SeniorFlex Mobility Aid', description: 'Joint supplement with glucosamine and MSM for senior cats.', image: 'https://images.unsplash.com/photo-1583337130417-3346a1f3e3c4?w=400&h=300&fit=crop' },
        { id: 34, name: 'ThyroidCare Feline Support', description: 'Special formula for cats with thyroid imbalance.', image: 'https://images.unsplash.com/photo-1601233741466-019d7d33d59b?w=400&h=300&fit=crop' },
        { id: 35, name: 'HeartEase Taurine Chews', description: 'Taurine-enriched chews for supporting feline heart health.', image: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=400&h=300&fit=crop' },
        { id: 36, name: 'RespiraPurr Cough Remedy', description: 'Mild herbal remedy for occasional coughing and throat irritation.', image: 'https://images.unsplash.com/photo-1572715376041-6d374f580bd7?w=400&h=300&fit=crop' },
        { id: 37, name: 'OmegaFur Skin & Coat Oil', description: 'Omega-rich oil supplement for shiny coat and reduced shedding.', image: 'https://images.unsplash.com/photo-1601758123837-1ec2e1e8eaf8?w=400&h=300&fit=crop' },
        { id: 38, name: 'HydraPurr Electrolyte Formula', description: 'Oral hydration support for cats during illness or heat stress.', image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400&h=300&fit=crop' },
        { id: 39, name: 'SeniorFlex Mobility Aid', description: 'Joint supplement with glucosamine and MSM for senior cats.', image: 'https://images.unsplash.com/photo-1583337130417-3346a1f3e3c4?w=400&h=300&fit=crop' },
        { id: 40, name: 'ThyroidCare Feline Support', description: 'Special formula for cats with thyroid imbalance.', image: 'https://images.unsplash.com/photo-1601233741466-019d7d33d59b?w=400&h=300&fit=crop' },
        { id: 41, name: 'HeartEase Taurine Chews', description: 'Taurine-enriched chews for supporting feline heart health.', image: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=400&h=300&fit=crop' },
        { id: 42, name: 'RespiraPurr Cough Remedy', description: 'Mild herbal remedy for occasional coughing and throat irritation.', image: 'https://images.unsplash.com/photo-1572715376041-6d374f580bd7?w=400&h=300&fit=crop' },
      ];
    } else if (petType === 'cats') {
      return [
        { id: 1, name: 'Meloxicam', description: 'Inhibits cyclooxygenase (COX), mainly COX-2, reducing inflammation, pain, and fever.', image: 'https://images.unsplash.com/photo-1551717743-49959800b1f6?w=400&h=300&fit=crop' },
        { id: 2, name: 'Ketoprofen', description: 'It inhibits the cyclooxygenase enzymes (COX-1 and COX-2), reducing the production of prostaglandins — chemicals responsible for inflammation, pain, and fever. This leads to its anti-inflammatory, analgesic (pain-relieving), and antipyretic (fever-reducing) effects.', image: 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=400&h=300&fit=crop' },
        { id: 3, name: 'Alphachymotrypsin', description: 'Alpha-chymotrypsin is a serine protease that breaks down proteins by cleaving peptide bonds, especially at aromatic amino acids (tyrosine, phenylalanine, tryptophan). It helps reduce inflammation, aid tissue repair, and decrease edema (swelling) in conditions like trauma or surgery.', image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop' },
        { id: 4, name: 'Carprofen', description: 'Carprofen works by inhibiting cyclooxygenase (COX) enzymes, particularly COX-2, which reduces the production of prostaglandins—chemicals responsible for pain, inflammation, and fever. This leads to reduced pain and inflammation, especially in conditions like arthritis or post-surgery recovery.', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop' },
        { id: 5, name: 'Dexamethasone', description: 'Dexamethasone works by binding to glucocorticoid receptors, leading to suppression of inflammation and immune responses. It decreases the production of inflammatory cytokines, inhibits prostaglandin synthesis, and reduces immune cell activity, making it effective for treating allergies, autoimmune diseases, and inflammation.', image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=300&fit=crop' },
        { id: 6, name: 'Prednisolone', description: 'Prednisolone works by binding to glucocorticoid receptors, leading to reduced inflammation and immune response. It inhibits the production of inflammatory mediators like prostaglandins and cytokines, helping to control conditions such as allergies, asthma, and autoimmune diseases.', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop' },
        { id: 7, name: 'Hydrocortisone', description: 'Hydrocortisone works by activating glucocorticoid receptors, leading to suppression of inflammation and immune responses. It decreases the production of pro-inflammatory cytokines and inhibits prostaglandin synthesis, helping manage conditions like skin inflammation, allergies, and adrenal insufficiency.', image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400&h=300&fit=crop' },
        { id: 8, name: 'Triamcinolone', description: 'Triamcinolone binds to glucocorticoid receptors, leading to suppression of inflammation and immune responses. It reduces the production of pro-inflammatory cytokines, inhibits prostaglandins, and decreases immune cell activity, making it effective for treating allergies, skin conditions, arthritis, and asthma.', image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop' },
        { id: 9, name: 'Drontal', description: 'Drontal is a broad-spectrum anthelmintic medication primarily used for deworming in pets (especially dogs and cats). Praziquantel paralyzes and destroys the outer layer of flatworms (tapeworms). Pyrantel pamoate targets roundworms and hookworms, paralyzing them and causing them to be expelled from the intestines. Febantel interferes with the worm metabolism and inhibits its ability to reproduce.', image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop' },
        { id: 10, name: 'Milbemax', description: 'Milbemax combines two active ingredients for broad-spectrum deworming. Milbemycin oxime binds to glutamate-gated chloride channels in parasite nerve cells, causing hyperpolarization, paralysis, and death. Praziquantel damages parasite cell membranes, causing muscle paralysis and structural disintegration, leading to immune elimination of the parasite.', image: 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=400&h=300&fit=crop' },
        { id: 11, name: 'Panacur', description: 'Panacur contains fenbendazole, a broad-spectrum anthelmintic that inhibits tubulin polymerization into microtubules, disrupting parasite intestinal cell function. This leads to nutrient absorption failure and parasite death. Effective against roundworms, hookworms, whipworms, and some tapeworms.', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop' },
        { id: 12, name: 'Albenidazole', description: 'Albendazole inhibits the polymerization of tubulin into microtubules in parasitic cells, disrupting their structure and metabolism, leading to parasite death. It also impairs glucose uptake, starving and eliminating the parasite.', image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=300&fit=crop' },
        { id: 13, name: 'Metronidazole', description: 'Metronidazole disrupts DNA synthesis in anaerobic microorganisms. It is reduced to reactive nitro radicals inside the microorganism, which bind to DNA, causing strand breakage and cell death. It is effective mainly against anaerobic bacteria and protozoa.', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop' },
        { id: 14, name: 'Imidocarb dipropionate', description: 'Imidocarb interferes with nucleic acid metabolism of protozoa by binding to DNA, disrupting replication and transcription. It may also inhibit polyamine synthesis, impairing parasite growth and viability. It is particularly effective against Babesia spp. due to accumulation in infected erythrocytes.', image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400&h=300&fit=crop' },
        { id: 15, name: 'Clindamycin', description: 'Clindamycin is a lincosamide antibiotic that inhibits protein synthesis in susceptible organisms. It binds to the 50S ribosomal subunit, blocking translocation during protein synthesis. In protozoa like Toxoplasma gondii and Plasmodium falciparum, it disrupts apicoplast function, leading to parasite death.', image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop' },
        { id: 16, name: 'Itraconazole', description: 'Itraconazole is an azole antifungal that inhibits the fungal cytochrome P450 enzyme (14α-demethylase). This prevents the conversion of lanosterol to ergosterol, an essential component of the fungal cell membrane. Disruption of ergosterol synthesis leads to increased membrane permeability and fungal cell death.', image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop' },
        { id: 17, name: 'Ketoconazole', description: 'Ketoconazole is an azole antifungal that inhibits lanosterol 14-α-demethylase (a cytochrome P450 enzyme), blocking the conversion of lanosterol to ergosterol. This destabilizes the fungal cell membrane and leads to fungal cell death.', image: 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=400&h=300&fit=crop' },
        { id: 18, name: 'Miconazole', description: 'Miconazole is an imidazole antifungal that inhibits ergosterol synthesis, a key component of fungal cell membranes. This disrupts membrane integrity, leading to increased permeability and fungal cell death.', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop' },
        { id: 19, name: 'Clavamox', description: 'Clavamox combines amoxicillin (a penicillin-type beta-lactam antibiotic) with clavulanic acid (a beta-lactamase inhibitor). Amoxicillin inhibits bacterial cell wall synthesis, causing cell lysis and death. Clavulanic acid protects amoxicillin from being broken down by beta-lactamase enzymes produced by resistant bacteria.', image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=300&fit=crop' },
        { id: 20, name: 'Amoxi-Tabs / Amoxi-Drops', description: 'Amoxi-Tabs and Amoxi-Drops are amoxicillin-only formulations. Amoxicillin works by inhibiting bacterial cell wall synthesis, leading to cell lysis and death. These forms are commonly prescribed for infections where beta-lactamase resistance is not a concern.', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop' },
        { id: 21, name: 'Ceftriaxone', description: 'Ceftriaxone is a broad-spectrum third-generation cephalosporin antibiotic used off-label in veterinary medicine, particularly for dogs and cats. It works by inhibiting bacterial cell wall synthesis through binding to penicillin-binding proteins (PBPs), leading to disruption of the cell wall, cell lysis, and bacterial death.', image: 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=400&h=300&fit=crop' },
        { id: 22, name: 'Metronidazole', description: 'Metronidazole is a widely used antibiotic and antiprotozoal agent. It is effective against anaerobic bacteria and protozoa. It works by being reduced inside anaerobic cells to reactive nitro radicals, which damage DNA, inhibit nucleic acid synthesis, and cause cell death. It selectively targets organisms with nitroreductase enzymes (anaerobes and protozoa). It has trade name of Flagyl (original brand by Sanofi).', image: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=400&h=300&fit=crop' },
        { id: 23, name: 'Baytril', description: 'Baytril is the brand name for enrofloxacin, a fluoroquinolone antibiotic. It works by inhibiting bacterial DNA gyrase and topoisomerase IV, enzymes necessary for DNA replication, transcription, and repair. This leads to bacterial cell death, making it bactericidal (kills bacteria rather than just inhibiting growth). It is widely used in dogs, cats, and other animals (including exotic species) for bacterial infections, especially when resistant to other antibiotics. Common indications include urinary tract infections (UTIs), skin infections (pyoderma), respiratory tract infections, wound infections, ear infections (otitis externa), gastrointestinal infections, prostatitis, and infections caused by Pseudomonas, E. coli, Staphylococcus, and other gram-negative and gram-positive bacteria. Baytril is not effective against anaerobic bacteria or fungi.', image: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=400&h=300&fit=crop' },
        { id: 24, name: 'Enroflox', description: 'Enroflox is a brand or generic name for enrofloxacin, a fluoroquinolone antibiotic. It inhibits bacterial DNA gyrase and topoisomerase IV — essential enzymes for DNA replication, transcription, and repair. This leads to rapid bacterial cell death (bactericidal). It is effective primarily against aerobic Gram-negative bacteria, and some Gram-positive bacteria. Enroflox is used in dogs, cats, and sometimes exotic animals or livestock. Common indications include skin infections (pyoderma, wounds), UTIs, respiratory infections, ear infections (otitis externa), gastrointestinal infections, bone and joint infections, prostatitis, and infections caused by E. coli, Klebsiella, Pasteurella, Staphylococcus, Pseudomonas, etc. Not effective against anaerobic bacteria or fungal infections.', image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400&h=300&fit=crop' },
        { id: 25, name: 'Cipromed', description: 'Cipromed contains ciprofloxacin, a fluoroquinolone antibiotic. It inhibits bacterial enzymes: DNA gyrase and topoisomerase IV, which are essential for DNA replication, repair, and transcription. Inhibition of these enzymes leads to bacterial DNA damage and cell death. Ciprofloxacin is bactericidal, primarily targeting aerobic gram-negative bacteria, and some gram-positive bacteria. Cipromed is primarily used in pets as an ophthalmic (eye drop) solution, though it may be prescribed off-label for other uses.', image: 'https://images.unsplash.com/photo-1601758123927-196f6b9f7b3f?w=400&h=300&fit=crop' },
        { id: 26, name: 'Ciprovet', description: 'Ciprovet contains ciprofloxacin, a fluoroquinolone antibiotic. It inhibits bacterial DNA gyrase and topoisomerase IV, enzymes required for bacterial DNA replication, repair, and transcription. This disruption leads to bacterial cell death. It is bactericidal and mainly effective against aerobic gram-negative bacteria and some gram-positive strains. Ciprovet is primarily used in dogs and cats for treating bacterial eye infections, though oral ciprofloxacin may occasionally be used off-label.', image: 'https://images.unsplash.com/photo-1596495577886-d920f1fb7238?w=400&h=300&fit=crop' },
        { id: 27, name: 'Amiglyde-V', description: 'Amiglyde-V contains amikacin sulfate, an aminoglycoside antibiotic. It works by binding irreversibly to the 30S ribosomal subunit of susceptible bacteria, inhibiting protein synthesis and producing faulty proteins, which leads to bacterial cell death. Amikacin is bactericidal and effective primarily against aerobic Gram-negative bacteria and some Gram-positive strains. It is typically reserved for serious infections that are resistant to other antibiotics.', image: 'https://images.unsplash.com/photo-1572715376041-6d374f580bd7?w=400&h=300&fit=crop' },
        { id: 28, name: 'Dog Liver Support Tablets', description: 'Herbal liver support for detox and health.', image: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400&h=300&fit=crop' },
        { id: 29, name: 'Dog Allergy Shampoo', description: 'Gentle shampoo for dogs with sensitive skin.', image: 'https://images.unsplash.com/photo-1561037404-61cd46aa6153?w=400&h=300&fit=crop' },
        { id: 30, name: 'Dog Recovery Kit', description: 'Complete post-op care kit for dogs after surgery.', image: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=400&h=300&fit=crop' },
        { id: 31, name: 'OmegaFur Skin & Coat Oil', description: 'Omega-rich oil supplement for shiny coat and reduced shedding.', image: 'https://images.unsplash.com/photo-1601758123837-1ec2e1e8eaf8?w=400&h=300&fit=crop' },
        { id: 32, name: 'HydraPurr Electrolyte Formula', description: 'Oral hydration support for cats during illness or heat stress.', image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400&h=300&fit=crop' },
        { id: 33, name: 'SeniorFlex Mobility Aid', description: 'Joint supplement with glucosamine and MSM for senior cats.', image: 'https://images.unsplash.com/photo-1583337130417-3346a1f3e3c4?w=400&h=300&fit=crop' },
        { id: 34, name: 'ThyroidCare Feline Support', description: 'Special formula for cats with thyroid imbalance.', image: 'https://images.unsplash.com/photo-1601233741466-019d7d33d59b?w=400&h=300&fit=crop' },
        { id: 35, name: 'HeartEase Taurine Chews', description: 'Taurine-enriched chews for supporting feline heart health.', image: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=400&h=300&fit=crop' },
        { id: 36, name: 'RespiraPurr Cough Remedy', description: 'Mild herbal remedy for occasional coughing and throat irritation.', image: 'https://images.unsplash.com/photo-1572715376041-6d374f580bd7?w=400&h=300&fit=crop' },
        { id: 37, name: 'OmegaFur Skin & Coat Oil', description: 'Omega-rich oil supplement for shiny coat and reduced shedding.', image: 'https://images.unsplash.com/photo-1601758123837-1ec2e1e8eaf8?w=400&h=300&fit=crop' },
        { id: 38, name: 'HydraPurr Electrolyte Formula', description: 'Oral hydration support for cats during illness or heat stress.', image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400&h=300&fit=crop' },
        { id: 39, name: 'SeniorFlex Mobility Aid', description: 'Joint supplement with glucosamine and MSM for senior cats.', image: 'https://images.unsplash.com/photo-1583337130417-3346a1f3e3c4?w=400&h=300&fit=crop' },
        { id: 40, name: 'ThyroidCare Feline Support', description: 'Special formula for cats with thyroid imbalance.', image: 'https://images.unsplash.com/photo-1601233741466-019d7d33d59b?w=400&h=300&fit=crop' },
        { id: 41, name: 'HeartEase Taurine Chews', description: 'Taurine-enriched chews for supporting feline heart health.', image: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=400&h=300&fit=crop' },
        { id: 42, name: 'RespiraPurr Cough Remedy', description: 'Mild herbal remedy for occasional coughing and throat irritation.', image: 'https://images.unsplash.com/photo-1572715376041-6d374f580bd7?w=400&h=300&fit=crop' },
      ];
    }
    
    // Default fallback (shouldn't be reached for valid pet types)
    return [];
  };

  const medicines = getMedicinesForPetType();

  const renderMedicineCard = (medicine: any) => {
    if (petType === 'dogs') {
      return (
        <DogMedicineCard
          key={medicine.id}
          id={medicine.id}
          name={medicine.name}
          description={medicine.description}
          image={medicine.image}
        />
      );
    } else if (petType === 'cats') {
      return (
        <CatMedicineCard
          key={medicine.id}
          id={medicine.id}
          name={medicine.name}
          description={medicine.description}
          image={medicine.image}
        />
      );
    }
    return null;
  };

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
      {medicines.map((medicine) => renderMedicineCard(medicine))}
    </div>
  );
};

export default MedicineGrid;
